packaging_format = 2

id = "x-prober"
name = "x-prober"
description.en = "Probe program for PHP environment"
description.fr = "Programme de test pour l'environnement PHP"

version = "8.18~ynh1"

maintainers = ["jarod5001"]

[upstream]
license = "GPL-3.0"
website = "https://prober.inn-studio.com/"
demo = "https://prober.inn-studio.com/"
code = "https://github.com/kmvan/x-prober"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "900M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/xprober"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/kmvan/x-prober/archive/refs/tags/8.18.tar.gz"
        sha256 = "e8ec6d3805cf005ad2644119b7f1950623772dcaf224999349b31cd850d35a85"
        in_subdir = false
        extract = false
        rename = "prober.php"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm"
    
